SET client_encoding = 'UTF8';

INSERT INTO movieland.bridge_movie_country VALUES (1, 1, 1);
INSERT INTO movieland.bridge_movie_country VALUES (2, 2, 1);
INSERT INTO movieland.bridge_movie_country VALUES (3, 3, 1);
INSERT INTO movieland.bridge_movie_country VALUES (4, 4, 1);
INSERT INTO movieland.bridge_movie_country VALUES (5, 5, 2);
INSERT INTO movieland.bridge_movie_country VALUES (6, 6, 1);
INSERT INTO movieland.bridge_movie_country VALUES (7, 6, 3);
INSERT INTO movieland.bridge_movie_country VALUES (8, 7, 4);
INSERT INTO movieland.bridge_movie_country VALUES (9, 8, 1);
INSERT INTO movieland.bridge_movie_country VALUES (10, 8, 5);
INSERT INTO movieland.bridge_movie_country VALUES (11, 9, 1);
INSERT INTO movieland.bridge_movie_country VALUES (12, 10, 1);
INSERT INTO movieland.bridge_movie_country VALUES (13, 11, 6);
INSERT INTO movieland.bridge_movie_country VALUES (14, 12, 1);
INSERT INTO movieland.bridge_movie_country VALUES (15, 13, 1);
INSERT INTO movieland.bridge_movie_country VALUES (16, 14, 6);
INSERT INTO movieland.bridge_movie_country VALUES (17, 15, 1);
INSERT INTO movieland.bridge_movie_country VALUES (18, 15, 3);
INSERT INTO movieland.bridge_movie_country VALUES (19, 16, 3);
INSERT INTO movieland.bridge_movie_country VALUES (20, 16, 1);
INSERT INTO movieland.bridge_movie_country VALUES (21, 17, 1);
INSERT INTO movieland.bridge_movie_country VALUES (22, 17, 3);
INSERT INTO movieland.bridge_movie_country VALUES (23, 18, 1);
INSERT INTO movieland.bridge_movie_country VALUES (24, 19, 1);
INSERT INTO movieland.bridge_movie_country VALUES (25, 20, 1);
INSERT INTO movieland.bridge_movie_country VALUES (26, 20, 5);
INSERT INTO movieland.bridge_movie_country VALUES (27, 21, 4);
INSERT INTO movieland.bridge_movie_country VALUES (28, 21, 7);
INSERT INTO movieland.bridge_movie_country VALUES (29, 21, 5);
INSERT INTO movieland.bridge_movie_country VALUES (30, 21, 1);
INSERT INTO movieland.bridge_movie_country VALUES (31, 22, 4);
INSERT INTO movieland.bridge_movie_country VALUES (32, 23, 4);
INSERT INTO movieland.bridge_movie_country VALUES (33, 24, 1);
INSERT INTO movieland.bridge_movie_country VALUES (34, 25, 1);
INSERT INTO movieland.bridge_movie_country VALUES (35, 25, 3);

SELECT pg_catalog.setval('movieland.bridge_movie_country_id_seq', 35, true);
